name: Swift CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Swift
      uses: swift-actions/setup-swift@v1
      with:
        swift-version: '5.9'

    - name: Build
      run: swift build -v

    - name: Run tests with coverage
      run: swift test --enable-code-coverage

    - name: Generate coverage report
      run: |
        xcrun llvm-cov export -format="lcov" .build/debug/PKSDependencyEnginePackageTests.xctest/Contents/MacOS/PKSDependencyEnginePackageTests -instr-profile .build/debug/codecov/default.profdata > coverage.lcov

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage.lcov
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: true

    - name: Output JUnit XML
      run: |
        xcrun xccov view --report --json coverage.lcov > coverage.json
        xcrun xccov report coverage.json --json --output-path coverage.junit.xml

    - name: Upload test results to Codecov
      if: ${{ !cancelled() }}
      uses: codecov/test-results-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
